### ISSUE TITLE
[cfp] Continuous Delivery with Git and K8S

### ISSUE THREAD

**Issue by wdalmut** [gianarb/devcampy.com#10]
**Title:** Continuous Delivery with Git and K8S
**Description:** In this talk we will discuss about continuous delivery and kubernetes. We will deploy our applications using Git and Pull Requests as main trigger for infrastructure changes. 
**Size:** 45min
**Bio:** Solutions Architect @ CorleyCloud
**Links:** @wdalmut on Twitter

**Comment by gianarb** [comment]
Hello!
Published: https://www.meetup.com/CNCF-Italy/events/266725822/

I know you have o change it a bit! Feel free to answer here again and to re-open the issue when you are done.

Thanks
