### ISSUE TITLE
[cfp] new talk proposal

### ISSUE THREAD

**Issue by endorama** [gianarb/devcampy.com#11]
**Title:** SRE: Making users happy
**Description:** At the end of the DevOps pipeline await the SRE team. 
What is Site Reliability Engineering, how it relates to shipping products? What does it mean for your customers, your development team, your business?

We are going to explore SRE toolbox and techniques you can use tomorrow to manage and improve service reliability.
**Size:** L(45min)
**Bio:** Operator by day, curious by night. What I do care most are people.

I started almost 10 years ago as Full Stack developer on a Ruby On Rails project, since then I worked with different languages, frameworks and teams, I always been in charge of system administration and keeping servers alive and was able to explore the UX side of web development.

I'm now focusing on applying and improving DevOps techniques at Arduino.

**Links:** 
- https://dev.to/endorama
- https://github.com/endorama
- https://twitter.com/edoardotenani

**Comment by gianarb** [comment]
Published:
https://www.meetup.com/CNCF-Italy/events/266725822/
