### ISSUE TITLE
[cfp] Kafka: the simplicity behind complexity

### ISSUE THREAD

**Issue by agile-lab** [gianarb/devcampy.com#12]
**Title:**  Kafka: the simplicity behind complexity

**Description:** 
Any system that excels in performance and is extremely reliable for mission critical scenarios has always one feature: is stupid. Kafka is not an exception to that.
We will discover how it achieve incredible performances and high availability with a simple and lean design.

**Size:** L(45min)
**Bio:** I'm the CTO of Agile Lab and Aim2 and I love distributed systems
**Links:** https://www.linkedin.com/in/paoloplatter/

**Comment by gianarb** [comment]
https://www.meetup.com/CNCF-Italy/events/267372907/?isFirstPublish=true
